### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by durka** [DevProgress/my-vote-matters#11]
Tentative plan: Github Pages with CloudFlare for SSL. Need to find & register a domain name.

**Comment by flibbertigibbet** [comment]
I believe Carrie already has a registered domain (she is not on GitHub).

**Comment by durka** [comment]
Update: she registered myvotematters.today and myvotematters.vote, and put out a bid on myvotematters.com.

**Comment by durka** [comment]
Soft-launched at https://myvotematters.today thanks to @decause and @phildini. The site is served from the master branch of the repository.
