### ISSUE TITLE
Photos posted from different devices will be different sizes

### ISSUE THREAD

**Issue by durka** [DevProgress/my-vote-matters#20]
#18 made the canvas auto-scale to the screen size, which is the same as the size of the final shared image. If we care about this, it could be fixed by redrawing to an invisible fixed-size canvas. However, different cameras still have different aspect ratios, so we'd have to pick either the height or width to hold constant.

**Comment by dglazkov** [comment]
Here's one idea: let's always draw the same size. Instead of trying to adapt the polaroid frame to the video size, crop/scale the video to always be the same size.

**Comment by ldworkin** [comment]
Discussed with @durka and going to close this issue -- it's not really a problem if different photos are different sizes! It was only going to be a problem if we were automatically showing new ones on our landing page (which we are not).
