### ISSUE TITLE
Update URL in Twitter auth request

### ISSUE THREAD

**Issue by uberdog** [DevProgress/my-vote-matters#27]
Currently it's myvotematters.com. Should be myvotematters.today.
<img width="669" alt="screen shot 2016-10-22 at 1 52 55 pm" src="https://cloud.githubusercontent.com/assets/1243310/19621394/057183a8-985f-11e6-83aa-69160299ed4e.png">

**Comment by durka** [comment]
@ldworkin has the keys to the Twitter app. This might affect the FB app as well.

**Comment by ldworkin** [comment]
Fixed!
