### ISSUE TITLE
Turn camera off after picture is taken

### ISSUE THREAD

**Issue by uberdog** [DevProgress/my-vote-matters#28]
I just took a picture and posted to Twitter. While the picture in the frame isn't updating, the camera is still on. This is shown in the browser tab and the LED on my laptop.

The camera should only be on when the user requests it, otherwise it's kind of creepy.
<img width="235" alt="screen shot 2016-10-22 at 1 59 07 pm" src="https://cloud.githubusercontent.com/assets/1243310/19621445/13197960-9860-11e6-8cf1-c5a011e7d41f.png">

**Comment by durka** [comment]
But will this cause a delay if you go back to take another pic?

**Comment by ldworkin** [comment]
Fixed!
