### ISSUE TITLE
Tweet Improvements

### ISSUE THREAD

**Issue by uberdog** [DevProgress/my-vote-matters#29]
Include #MyVoteMatters in tweet body.

Currently the text of the tweet is only what the user wrote, so there's no context and the hashtag never actually shows up in the tweet except in the image.

Also, the "message" is repeated twice. Once in the tweet text and once in the image.

<img width="597" alt="screen shot 2016-10-22 at 2 03 10 pm" src="https://cloud.githubusercontent.com/assets/1243310/19621532/dac1ffd6-9861-11e6-968a-27d098376c2a.png">

**Comment by durka** [comment]
I think we should include the full text in the tweet, i.e. "#MyVoteMatters because I'm testing". The repetition doesn't bother me.
