### ISSUE TITLE
Reset state after taking picture

### ISSUE THREAD

**Issue by flibbertigibbet** [DevProgress/my-vote-matters#3]
Currently requires page reload to be able to take another picture.

**Comment by ldworkin** [comment]
Should be fixed by https://github.com/DevProgress/my-vote-matters/commit/05e7c0b228a0644b179cb93c56426e3558467dab

**Comment by durka** [comment]
I broke this again in #13 😳

**Comment by durka** [comment]
I wonder if it should reset after you share once, or leave the share buttons up so you can click the other one?

**Comment by ldworkin** [comment]
Fixed in 1e47367aab7687336cb88c408a847f0278c4a8c5
