### ISSUE TITLE
Timeline: autosize text in header/footer

### ISSUE THREAD

**Issue by durka** [DevProgress/my-vote-matters#32]
There's some code in js/main.js to autosize the text of the carousel and footer according to screen/window size, but it isn't included in timeline/index.html so the footer text doesn't scale.

Likely we should do this in some way without JS anyway.

cc #27 @eyas

**Comment by ldworkin** [comment]
@durka Why not just copy the javascript function into timeline/index.html? We probably _could_ figure out a better non-JS way, but if we already have a solution ... :)

**Comment by ldworkin** [comment]
Also @Eyas can I see a screenshot of this scrolling issue?

**Comment by ldworkin** [comment]
Ok sorry to spam this thread, but will this PR take care of it -- https://github.com/DevProgress/my-vote-matters/pull/33? Like @durka says it doesn't work on Android < 4.4 but I'm willing to take that hit!

**Comment by dglazkov** [comment]
@durka, where did you get that information? Chrome auto-updates on all versions of Android.

**Comment by durka** [comment]
Fixed by #33.
