### ISSUE TITLE
Safari upload will change an image's aspect ratio

### ISSUE THREAD

**Issue by ldworkin** [DevProgress/my-vote-matters#43]
When you upload an image using Safari (which you have to do because the camera doesn't work there) it ends up being "squished" to fit a given aspect ratio.

<img width="360" alt="screen_shot_2016-10-23_at_6 52 46_pm_720" src="https://cloud.githubusercontent.com/assets/1062275/19652902/8b5afbca-99e0-11e6-9bb5-9fb46cbd1793.png">

**Comment by dglazkov** [comment]
Fixed now.
