### ISSUE TITLE
fix layout on mobile

### ISSUE THREAD

**Issue by durka** [DevProgress/my-vote-matters#5]
- [x] ~~The Polaroid image doesn't adapt to the actual size of the video.~~ (fixed by #6)
- [x] ~~The video canvas isn't centered (on my phone it's jammed up against the right side).~~ (also #6)
- [ ] The video size doesn't always adapt correctly when the screen is rotated.
- [ ] In landscape mode, the popup is too large, preventing you from getting to the text entry.

**Comment by dglazkov** [comment]
This is superseded by #8 right?

**Comment by durka** [comment]
Mostly, I guess. The screen rotation and popup size issues are more technical than content-related.
