### ISSUE TITLE
Camera button doesn't launch camera on iOS

### ISSUE THREAD

**Issue by durka** [DevProgress/my-vote-matters#55]
My mother reports that on her iPhone 6, the option to launch the camera results in something that _looks_ like the camera, but the image is blank. Uploading an image from the camera roll does work.

**Comment by durka** [comment]
cc @dglazkov ?

**Comment by dglazkov** [comment]
I am going to guess that the user clicked "Deny" when asked for camera permission one time.

**Comment by durka** [comment]
Turns out the page was loaded in the FB app (presumably from the link in my post) so it was FB that needed camera permissions. Sounds like it's not something that can be fixed on our end.
