### ISSUE TITLE
Users are unable to share on Facebook

### ISSUE THREAD

**Issue by dglazkov** [DevProgress/my-vote-matters#68]
The user reports seeing "Sorry, something went wrong." consistently. However, other users seem to be having no issues.

**Comment by durka** [comment]
Google Analytics does not seem to be catching most of the exceptions we [send](https://github.com/DevProgress/my-vote-matters/blob/421e29698cf7a8afb4de95ee72ed415b62015af1/js/main.js#L442), no idea why, but out of the five events it's showing, the three error messages are "OAuth object must be initialized" (another race?) and "The popup was closed" (which doesn't make sense to me -- of course it was closed, after it performed its function!), and, unfortunately, "[object Object]".

**Comment by dglazkov** [comment]
Let me try to troubleshoot directly w/the user

**Comment by dglazkov** [comment]
This problem is not specific to one user. We don't ask for sufficient permissions on Facebook. In testing (created a temporary "clean" Facebook account), I see the same issue.

**Comment by ldworkin** [comment]
Closing this because now sharing _does_ work even though buggy (and there's another issue for that)
