### ISSUE TITLE
Scaling images could be better

### ISSUE THREAD

**Issue by dglazkov** [DevProgress/my-vote-matters#69]
Since we're doing a simple scaling of an image, the output could end up looking pixelated. We should consider using a more sophisticated scaling algorithm.

**Comment by andrewjtimmons** [comment]
Do you have a screenshot of it looking pixelated or know what platforms have this issue?  I used my macbook camera, which I know is not the highest resolution, but it looked p good.  

![csqhldy](https://cloud.githubusercontent.com/assets/1569764/19972690/45b32a44-a1b9-11e6-921c-606631d973b8.png)
