### ISSUE TITLE
Show sample #myvotematters selfies on background of landing page

### ISSUE THREAD

**Issue by durka** [DevProgress/my-vote-matters#7]
We could collect them live from Twitter/FB but it's probably better to just curate a few and serve them statically.

**Comment by durka** [comment]
#18 adds tiled images behind the main view. Right now it just copies our one sample image as many times as necessary to fill the screen. Clearly some variety should be added :)

**Comment by ldworkin** [comment]
The background is now white -- we want it to look like https://devprogress.slack.com/?redir=%2Ffiles-pri%2FT1AJ4F4KC-F2Q15B58T%2Fversion_2_edited.png.

**Comment by ldworkin** [comment]
See https://github.com/DevProgress/my-vote-matters/pull/45. Just needs the real images to be added!

**Comment by dglazkov** [comment]
Done.
