### ISSUE TITLE
On a shorter screen, the "Take photo" button is below the fold

### ISSUE THREAD

**Issue by dglazkov** [DevProgress/my-vote-matters#72]
On one user's screen, they were not sure how to take a picture, because the button was below the fold.

**Comment by Burtchen** [comment]
I'll get on that. Do we have any specific on what the "shorter" screen was specifically?

**Comment by Burtchen** [comment]
(Still waiting for information/specifics)

**Comment by dglazkov** [comment]
My apologies. This issue was reported by Perry, and I thought you talked with him on slack about this?

**Comment by Burtchen** [comment]
Coincidentally, I discovered the issue myself this morning while testing on a Fire tablet. It's not so much just a 'shorter' screen but screen with certain proportions. As the conflicting issue about some general reorganisation of the layout seem to take their sweet little time, I'll have another look into ensuring the button always appears.
