### ISSUE TITLE
Download button doesn't work on iOS Chrome

### ISSUE THREAD

**Issue by durka** [DevProgress/my-vote-matters#74]
It seems to just load the data URI into the address bar.

![](http://i.imgur.com/PiE65u1.jpg)

[This SO question](http://stackoverflow.com/questions/24485077/how-to-open-blob-url-on-chrome-ios) might be relevant.

**Comment by durka** [comment]
A possible solution here is to abandon the automatic downloading function and instead just upload the image to imgur and link to that. We have the imgur capability now thanks to @ldworkin's FB refactoring branch that I am about to merge.

**Comment by dglazkov** [comment]
SGTM. I can tackle this tonight.

**Comment by durka** [comment]
Fixed as well as we can by #84.
