### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by durka** [DevProgress/my-vote-matters#76]
We need a privacy policy to be a well behaved FB app. We do not collect or store any information, let alone user information, so it should not be hard to write.

**Comment by durka** [comment]
This does not seem to prevent FB sharing from working.

**Comment by ldworkin** [comment]
I think this was only showing up because I had opened an application for review (since we thought we needed it) but I just deleted the application, so it shouldn't appear again (let me know if it does).
