### ISSUE TITLE
iOS Safari/Chrome experience confusing due to lack of getUserMedia support

### ISSUE THREAD

**Issue by Burtchen** [DevProgress/my-vote-matters#87]
As currently mobile (and desktop) Safari do not support getUserMedia, users on iOS devices are presented with the standard "Oops, your camera won't work here" UI. However, once the user click's on "Upload picture", iOS offers an option to take one, so the user is getting mixed messages and thus very confused.

Instead, we could change the text to direct the user to upload OR take a picture on an iOS device. This would minimize the user's irritation.

**Comment by dglazkov** [comment]
I landed #91 just now to tweak the text.
