### ISSUE TITLE
On Chrome When the Browser is Denied Camera Access, Unable to Upload Photo, Button makes Infinite TELL US HOW YOU FEEL 

### ISSUE THREAD

**Issue by elevati0n** [DevProgress/my-vote-matters#94]
Hi, if I disallow the browser access to my camera, the 'take picture' button never goes away nor does the 'enter text dialog' pop up.
however if i click on the photo but not the button BEFORE clicking the camera, I am able to enter a captin but still can't upload a file.

I am running chromium on macOSX macbook air 2011 
![image](https://cloud.githubusercontent.com/assets/7454313/20035118/05e43dbc-a3ae-11e6-96f5-cbeb9eca68cb.png)

i can click it repeatedly 

![image](https://cloud.githubusercontent.com/assets/7454313/20035125/15fe1736-a3ae-11e6-92b5-a028b4f5a328.png)

If i dont click the button, i can enter text by clicking on the main photo, however I still cant upload a file.  I can even share to twitter

![image](https://cloud.githubusercontent.com/assets/7454313/20035139/56ad73c6-a3ae-11e6-9292-26f405a6ec58.png)

![image](https://cloud.githubusercontent.com/assets/7454313/20035128/21b988f8-a3ae-11e6-945f-8404d177520b.png)

The easiest fix I can think of would be to always have the text input button and the file upload button available and just use the SAVE as the interim between uploading , capturing and entering text.  and then maybe have a check there is a file ?  or maybe sharing black files isnt too bad cos the message will still be there, but yeah, as of right now the site is unusable for me.

**Comment by ldworkin** [comment]
Should be fixed now!
